version: '3.9'

services:
  database:
    image: postgres:16rc1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=virtual_store
    ports:
      - "5500:5432"
    container_name: database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 10s
      retries: 5
    restart: "always"
    volumes:
      - "./backend/database:/var/lib/postgresql/data"
    networks:
      - e-commerce

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8081:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - "./backend:/home/src"
    networks:
      e-commerce:
        ipv4_address: 192.168.10.14

networks:
  e-commerce:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
